version: 2

project_name: nbu_exporter

before:
  hooks:
    # Assure que les dépendances sont à jour
    - go mod tidy

builds:
  - # Définit la compilation principale
    main: ./main.go
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - # Archives pour les différentes plateformes
    # Windows utilise automatiquement .zip, les autres .tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.yaml

# dockers:
#   - # Image Docker multi-architecture
#     dockerfile: Dockerfile.goreleaser
#     image_templates:
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default \"fjacquet\" }}/{{ .ProjectName }}:{{ .Version }}"
#       - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default \"fjacquet\" }}/{{ .ProjectName }}:latest"
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/amd64,linux/arm64"
#       - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#       - "--label=org.opencontainers.image.version={{ .Version }}"
#       - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER | default \"fjacquet\" }}/{{ .ProjectName }}"
#     extra_files:
#       - config.yaml

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "README"
  groups:
    - title: Features
      regexp: "^feat:"
      order: 0
    - title: Bug Fixes
      regexp: "^fix:"
      order: 1
    - title: Others
      order: 999
