version: 2

project_name: nbu_exporter

before:
  hooks:
    # Assure que les dépendances sont à jour
    - go mod tidy

builds:
  - # Définit la compilation principale
    main: ./main.go
    binary: "{{ .ProjectName }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - # Archives pour les différentes plateformes
    # Windows utilise automatiquement .zip, les autres .tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - config.yaml

dockers:
  - image_templates:
      - "ghcr.io/fjacquet/nbu_exporter:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/fjacquet/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
    extra_files:
      - config.yaml
  - image_templates:
      - "ghcr.io/fjacquet/nbu_exporter:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/fjacquet/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
    extra_files:
      - config.yaml

docker_manifests:
  - name_template: "ghcr.io/fjacquet/nbu_exporter:{{ .Version }}"
    image_templates:
      - "ghcr.io/fjacquet/nbu_exporter:{{ .Version }}-amd64"
      - "ghcr.io/fjacquet/nbu_exporter:{{ .Version }}-arm64"
  - name_template: "ghcr.io/fjacquet/nbu_exporter:latest"
    image_templates:
      - "ghcr.io/fjacquet/nbu_exporter:{{ .Version }}-amd64"
      - "ghcr.io/fjacquet/nbu_exporter:{{ .Version }}-arm64"

brews:
  - repository:
      owner: fjacquet
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/fjacquet/nbu_exporter"
    description: "Prometheus exporter for Veritas NetBackup"
    license: "MIT"
    test: |
      system "#{bin}/nbu_exporter", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "README"
  groups:
    - title: Features
      regexp: "^feat:"
      order: 0
    - title: Bug Fixes
      regexp: "^fix:"
      order: 1
    - title: Others
      order: 999
