{
 "title": "NBU Statistics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "storage_unit",
    "label": "Storage unit",
    "query": {
     "query": "label_values(nbu_disk_bytes, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stockage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Advanced storage - % Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nbu_disk_bytes{name=~\"$storage_unit\",size=\"used\"})/sum(nbu_disk_bytes{name=~\"$storage_unit\"})*100",
     "legendFormat": "% Used"
    }
   ]
  },
  {
   "title": "Dedup storage - % Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nbu_disk_bytes{name=~\"$storage_unit\",size=\"used\"})/sum(nbu_disk_bytes{name=~\"$storage_unit\"})*100",
     "legendFormat": "% Used"
    }
   ]
  },
  {
   "title": "Volume sauvegarde",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nbu_jobs_bytes{action=\"BACKUP\"}",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  { "title": "Resume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Status incomplet",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nbu_status_count{action=\"BACKUP\",status!=\"0\"}",
     "legendFormat": "{{status}} "
    }
   ]
  },
  {
   "title": "Backup session",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nbu_status_count{action=\"BACKUP\"}",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "title": "Return code ratio",
   "type": "stat",
   "description": "return code 0 = backup OK",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "nbu_status_count", "legendFormat": "{{action}} rc {{status}}" }
   ]
  },
  {
   "title": "Backup  Session",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nbu_jobs_count{action=\"BACKUP\"}",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Backup  Total",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nbu_jobs_bytes{action=\"BACKUP\"}",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Sessions de sauvegarde",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "VMware",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"VMWARE\",action=\"BACKUP\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "NDMP",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"NDMP\"}",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": " Unix",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"STANDARD\"}",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Windows",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"MS-Windows\"}",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "Exchange",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"MS-Exchange-Server\"}",
       "legendFormat": "{{policy_type}}"
      }
     ]
    },
    {
     "title": "SQL Server",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"MS-SQL-SERVER\"}",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Oracle",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"ORACLE\"}",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Catalog",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_count{policy_type=\"NBU-Catalog\"}",
       "legendFormat": "Session"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume de backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "VMware",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"VMWARE\"}",
       "legendFormat": "Taille"
      }
     ]
    },
    {
     "title": "NDMP",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"NDMP\"}",
       "legendFormat": "Taille"
      }
     ]
    },
    {
     "title": "Unix",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"STANDARD\"}",
       "legendFormat": "Taille"
      }
     ]
    },
    {
     "title": "Windows",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"MS-Windows\"}",
       "legendFormat": "Taille"
      }
     ]
    },
    {
     "title": "Exchange",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"MS-Exchange-Server\"}",
       "legendFormat": "Taille"
      }
     ]
    },
    {
     "title": "SQL Server",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"MS-SQL-SERVER\"}",
       "legendFormat": "Taille"
      }
     ]
    },
    {
     "title": "Oracle",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"ORACLE\"}",
       "legendFormat": "Taille"
      }
     ]
    },
    {
     "title": "Catalog",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nbu_jobs_bytes{action=\"BACKUP\",policy_type=\"NBU-Catalog\"}",
       "legendFormat": "Taille"
      }
     ]
    }
   ]
  }
 ]
}